# Generated by Django 4.2.4 on 2023-08-13 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutMeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=500)),
                ("img_url", models.ImageField(upload_to="")),
                ("email_id", models.EmailField(max_length=254)),
                ("ig_url", models.URLField()),
                ("twitter_url", models.URLField()),
                ("linkdin_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="imageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="TagsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="PostModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=75)),
                ("subHeading", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("content", models.CharField(max_length=10000)),
                ("tags", models.ManyToManyField(to="api.tagsmodel")),
            ],
        ),
        migrations.CreateModel(
            name="ImagesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.IntegerField()),
                (
                    "images",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.imagemodel"
                    ),
                ),
            ],
        ),
    ]
