# Generated by Django 4.2.4 on 2023-08-13 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_aboutmemodel_img_url"),
    ]

    operations = [
        migrations.RemoveField(model_name="imagesmodel", name="post_id",),
        migrations.AddField(
            model_name="imagesmodel",
            name="post",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                to="api.postmodel",
            ),
        ),
    ]
