# Generated by Django 4.2.4 on 2023-08-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_imagesmodel_post_id_imagesmodel_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagemodel",
            name="image",
            field=models.ImageField(upload_to="api/"),
        ),
    ]
