# Generated by Django 4.2.4 on 2023-08-15 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_imagemodel_image_alter_imagesmodel_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagemodel",
            name="image",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.imagesmodel",
            ),
        ),
        migrations.AlterField(
            model_name="imagesmodel",
            name="post",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.postmodel",
            ),
        ),
    ]
