# Generated by Django 4.2.4 on 2023-08-15 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_imagemodel_image_alter_imagesmodel_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagemodel",
            name="image",
            field=models.ImageField(default="", upload_to="api/"),
        ),
        migrations.AlterField(
            model_name="imagesmodel",
            name="images",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.imagemodel",
            ),
        ),
    ]
