# Generated by Django 4.2.4 on 2023-08-15 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_remove_imagesmodel_images_imagesmodel_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagesmodel",
            name="mainPic",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.imagemodel",
            ),
        ),
        migrations.AlterField(
            model_name="imagesmodel",
            name="images",
            field=models.ManyToManyField(
                default="", related_name="post_images", to="api.imagemodel"
            ),
        ),
    ]
